{{- $pkg := "thanos" }}
{{- $fluxSettingsThanos := merge .Values.addons.thanos.flux .Values.flux -}}
{{- if (get .Values.addons $pkg).enabled }}
{{- $istioEnabled := eq (include "istioEnabled" .) "true" }}
{{- $havePostRenderers := (get .Values.addons $pkg).postRenderers }}
{{- $installServiceMonitorPostRenderers := and .Values.monitoring.enabled $istioEnabled (ne (include "ambientEnabled" .) "true") (eq (dig "istio" "mtls" "mode" "STRICT" .Values.addons.thanos.values) "STRICT") }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: {{ $pkg }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $pkg }}
    {{- include "commonLabels" . | nindent 4}}
  annotations:
    checksum/bigbang-values: {{ include (print $.Template.BasePath "/thanos/values.yaml") . | sha256sum }}
spec:
  releaseName: {{ $pkg }}
  targetNamespace: {{ $pkg }}
  {{- include "bigbang.helmRelease.chartSpec" (dict "name" "thanos" "package" (get .Values.addons $pkg) "root" .) | nindent 2 }}

  {{- toYaml $fluxSettingsThanos | nindent 2 }}

  {{- if or $havePostRenderers $installServiceMonitorPostRenderers }}
  postRenderers:
  {{- if $havePostRenderers }}
  {{ toYaml (get .Values.addons $pkg).postRenderers | nindent 4 }}
  {{- end }}
  {{- if $installServiceMonitorPostRenderers }}
  {{ include "thanos.serviceMonitorPostRenderers" . | nindent 2 }}
  {{- end }}
  {{- end }}
  {{- include "bigbang.helmRelease.valuesFrom" (dict "name" "thanos" "root" .) | nindent 2 }}

  {{- if or $istioEnabled .Values.kyvernoPolicies.enabled .Values.monitoring.enabled }}
  dependsOn:
  {{- if $istioEnabled }}
    {{- include "istioHelmReleases" . | nindent 4 }}
  {{- end }}
  {{- if .Values.kyvernoPolicies.enabled }}
    - name: kyverno-policies
      namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- if .Values.monitoring.enabled }}
    - name: monitoring
      namespace: {{ .Release.Namespace }}
  {{- end }}
  {{- end }}
{{- end }}
