{{- include "bigbang.normalizePackageAliases" . -}}
{{- $pkg := "thanos" }}
{{- if (get .Values.addons $pkg).enabled }}
{{- include "bigbang.imagePullSecret" (dict "root" . "namespace" $pkg "appName" $pkg) }}
{{- end }}
