{{- include "bigbang.normalizePackageAliases" . -}}
{{- if .Values.fluentbit.enabled }}
{{- include "bigbang.imagePullSecret" (dict "root" . "namespace" "fluentbit" "appName" "fluentbit" "component" "core") }}
{{- end }}
