{{- include "bigbang.normalizePackageAliases" . -}}
{{- if or .Values.addons.minioOperator.enabled .Values.addons.minio.enabled }}
{{- include "bigbang.namespace" (dict "root" . "name" "minio-operator" "appName" "minioOperator" "component" "application-utilities" "package" .Values.addons.minioOperator) }}
{{- end }}
