{{- include "bigbang.normalizePackageAliases" . -}}
{{- if .Values.elasticsearchKibana.enabled }}
{{- include "bigbang.namespace" (dict "root" . "name" "logging" "appName" "logging" "component" "core" "package" .Values.elasticsearchKibana) }}
{{- end }}
