# yaml-language-server: $schema=https://raw.githubusercontent.com/helm-unittest/helm-unittest/main/schema/helm-testsuite.json
suite: Package - Authservice - Redis Values Tests
templates:
  - templates/authservice/values.yaml
tests:
  - it: should prefer global external Redis in routes and network policies
    postRenderer:
      cmd: "sh"
      args:
        - "-c"
        - "yq eval '.stringData.defaults' - | yq eval '.'"
    set:
      addons.authservice.enabled: true
      addons.authservice.values.global.redis_server_uri: tcp://redis.example.internal:6379
      addons.authservice.chains.minimal.redis_server_uri: tcp://chain-redis.example.internal:6379
    asserts:
      - equal:
          path: routes.outbound["external-redis"].enabled
          value: true
      - equal:
          path: routes.outbound["external-redis"].hosts[0]
          value: redis.example.internal
      - equal:
          path: routes.outbound["external-redis"].ports[0].number
          value: 6379
      - equal:
          path: networkPolicies.egress.from.authservice.to.definition.redis-subnets
          value: true
      - equal:
          path: networkPolicies.ingress.to["redis-bb:6379"].from.k8s["monitoring/grafana"]
          value: false
  - it: should account for chain-level external Redis in routes and network policies
    postRenderer:
      cmd: "sh"
      args:
        - "-c"
        - "yq eval '.stringData.defaults' - | yq eval '.'"
    set:
      addons.authservice.enabled: true
      addons.authservice.values.redis.enabled: true
      addons.authservice.chains.minimal.redis_server_uri: tcp://chain-redis.example.internal:6379
    asserts:
      - equal:
          path: routes.outbound["external-redis"].enabled
          value: true
      - equal:
          path: routes.outbound["external-redis"].hosts[0]
          value: chain-redis.example.internal
      - equal:
          path: networkPolicies.egress.from.authservice.to.definition.redis-subnets
          value: true
