{{- include "bigbang.normalizePackageAliases" . -}}
{{- if .Values.gatekeeper.enabled }}
{{- include "bigbang.imagePullSecret" (dict "root" . "namespace" "gatekeeper-system" "appName" "gatekeeper" "component" "core") }}
{{- end }}
