{{- include "bigbang.normalizePackageAliases" . -}}
{{- if .Values.twistlock.enabled }}
{{- include "bigbang.imagePullSecret" (dict "root" . "namespace" "twistlock" "appName" "twistlock" "component" "security") }}
{{- end }}
