{{- include "bigbang.normalizePackageAliases" . -}}
{{- if .Values.renovate.enabled }}
{{- include "bigbang.imagePullSecret" (dict "root" . "namespace" "renovate" "appName" "renovate" "component" "core") }}
{{- end }}
