{{- include "bigbang.normalizePackageAliases" . -}}
{{- if .Values.neuvector.enabled }}
{{- include "bigbang.imagePullSecret" (dict "root" . "namespace" "neuvector" "appName" "neuvector" "component" "sandbox") }}
{{- end }}
