{{- include "bigbang.normalizePackageAliases" . -}}
{{- if .Values.neuvector.enabled }}
{{- include "bigbang.namespace" (dict "root" . "name" "neuvector" "appName" "neuvector" "component" "sandbox" "package" .Values.neuvector) }}
{{- end }}
