{{- if and (eq .Values.ztunnel.sourceType "git") (not .Values.offline) (eq (include "ambientEnabled" .) "true") }}
{{- include "bigbang.gitRepository" (dict "name" "ztunnel" "gitCredsName" "ztunnel" "git" .Values.ztunnel.git "component" "core" "root" .) }}
{{- end }}
