{{- range .Values.helmRepositories }}
{{- if .cosignPublicKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .name }}-cosign-pub
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "commonLabels" $ | nindent 4 }}
type: Opaque
data:
  cosign.pub: {{ .cosignPublicKey | b64enc }}
{{- end }}
---
{{- end }}
