{{- include "bigbang.normalizePackageAliases" . -}}
{{- if .Values.helmRepositories }}
{{- include "bigbang.imagePullSecret" (dict "root" . "namespace" .Release.Namespace "commonLabels" true) }}
{{- end }}
