{{- include "bigbang.normalizePackageAliases" . -}}
{{- /* Used for pulling images from custom registries.  One per namespace */ -}}
{{- if ( include "imagePullSecret" . ) }}
{{- range $ns := compact (splitList " " (include "uniqueNamespaces" (merge (dict "constraint" "namespace.createRegistrySecret" "default" true) .))) -}}
{{- include "bigbang.imagePullSecret" (dict "root" $ "namespace" $ns "appName" "private-registry") }}
---
{{- end -}}
{{- end -}}
