{{- include "bigbang.normalizePackageAliases" . -}}
{{- if .Values.prometheusOperatorCRDs.enabled }}
{{- include "bigbang.imagePullSecret" (dict "root" . "namespace" "monitoring" "appName" "monitoring" "component" "core") }}
{{- end }}
