{{- include "bigbang.normalizePackageAliases" . -}}
{{- $gitCredsSecretDict := dict
  "name" "certManager"
  "targetScope" .Values.certManager
  "releaseName" .Release.Name
  "releaseNamespace" .Release.Namespace
}}
{{- include "gitCredsSecret" $gitCredsSecretDict | nindent 0 -}}
