{{- include "bigbang.normalizePackageAliases" . -}}
{{- if .Values.certManager.enabled }}
{{- include "bigbang.imagePullSecret" (dict "root" . "namespace" .Values.certManager.namespace.name "appName" "cert-manager" "component" "core") }}
{{- end }}
