{{- include "bigbang.normalizePackageAliases" . -}}
{{- if .Values.addons.keycloak.enabled }}
{{- $name := "keycloak" }}
{{- $component := "security-tools" }}
{{- include "bigbang.imagePullSecret" (dict "root" . "namespace" $name "appName" $name "component" $component) }}
{{- end }}
