{{- include "bigbang.normalizePackageAliases" . -}}
{{- if .Values.addons.keycloak.enabled }}
{{ $name := "keycloak" }}
{{- include "bigbang.namespace" (dict "root" . "name" $name "appName" $name "component" "security-tools" "package" .Values.addons.keycloak) }}
{{- end }}
