{{- include "bigbang.normalizePackageAliases" . -}}
{{- if .Values.addons.velero.enabled }}
{{- include "bigbang.imagePullSecret" (dict "root" . "namespace" "velero" "appName" "velero" "component" "cluster-utilities") }}
{{- end }}
