{{- include "bigbang.normalizePackageAliases" . -}}
{{- if .Values.addons.gitlab.enabled }}
{{- include "bigbang.imagePullSecret" (dict "root" . "namespace" "gitlab" "appName" "gitlab" "component" "developer-tools") }}
{{- end }}
