{{- include "bigbang.normalizePackageAliases" . -}}
{{- if .Values.addons.gitlabRunner.enabled }}
{{- include "bigbang.imagePullSecret" (dict "root" . "namespace" "gitlab-runner" "appName" "gitlab-runner" "component" "developer-tools") }}
{{- end }}
