{{- /* Used for creating values for the package's Helm chart */ -}}
{{- range $pkgKey, $vals := .Values.packages -}}
{{- if (dig "enabled" true $vals) -}}
{{- $pkg := include "resourceName" $pkgKey -}}
{{- $defaults := $.Files.Get (printf "defaults/%s.yaml" $pkg) -}}
{{- if $defaults -}}
{{- $vals := mergeOverwrite $vals ($defaults | fromYaml).package -}}
{{- end -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $pkg }}-values
  namespace: {{ if dig "helmRelease" "namespace" nil (index $.Values.packages $pkgKey) }}
               {{ dig "helmRelease" "namespace" "" (index $.Values.packages $pkgKey) }}
             {{ else }}
               {{ default (dig "namespace" "name" $pkg $vals) "" }}
             {{ end }}
  labels:
    {{- include "commonLabels" $ | nindent 4 }}
type: Opaque
stringData:
{{- if (not $vals.kustomize) }}
{{- if dig "bbCommonValues" false $vals }}
{{- $istioEnabled := eq (include "istioEnabled" $) "true" -}}
{{- $istioHardened := dig "hardened" "enabled" false $.Values.istiod.values }}
  common.yaml: |
    global:
      domain: {{ $.Values.domain }}
      monitoring:
        enabled: {{ $.Values.monitoring.enabled }}
    bb-common:
      istio:
        enabled: {{ $istioEnabled }}
        ambient:
          enabled: {{ include "ambientEnabled" $ }}
        sidecar:
          enabled: {{ $istioHardened }}
        authorizationPolicies:
          enabled: {{ $istioHardened }}
          generateFromNetpol: {{ $istioHardened }}
      networkPolicies:
        hbonePortInjection:
          enabled: {{ include "ambientEnabled" $ }}
{{- pick $.Values.networkPolicies "enabled" "hbonePortInjection" "prependReleaseName" "defaultsAsHooks" "egress" "ingress" "additionalPolicies" "additional" | toYaml | nindent 8 }}
  {{- end }}

  {{- if or ($vals.values) (dig "passBigBangValues" true $vals) }}
  values.yaml: |-
    {{ if (dig "passBigBangValues" true $vals) -}}
    bigbang:
      {{- include "values-bigbang" $.Values | nindent 6 }}
    {{- end }}
    {{- if $vals.values -}}
    {{- tpl (toYaml $vals.values) $ | nindent 4 }}
    {{- end }}
  {{ else }}
  values.yaml: "{}"
  {{- end }}

  {{- else }}
  {{- if or ($vals.values) (dig "passBigBangValues" true $vals) }}
  {{- if (dig "passBigBangValues" true $vals) }}
  bigbang: |-
    {{- include "values-bigbang" $.Values | nindent 6 }}
  {{- end }}
  {{- if $vals.values -}}
  {{- tpl (toYaml $vals.values) $ | nindent 2 }}
  {{- end }}
  {{- else }}
  {}
  {{- end }}

  {{ end }}
  
---
{{ end -}}
{{- end -}}
