{{- include "bigbang.normalizePackageAliases" . -}}
{{- if or .Values.kyverno.enabled .Values.kyvernoPolicies.enabled .Values.kyvernoReporter.enabled }}
{{- include "bigbang.imagePullSecret" (dict "root" . "namespace" "kyverno" "appName" "kyverno" "component" "core") }}
{{- end }}
