{{- include "bigbang.normalizePackageAliases" . -}}
{{- if or .Values.kyverno.enabled .Values.kyvernoPolicies.enabled .Values.kyvernoReporter.enabled }}
{{- include "bigbang.namespace" (dict "root" . "name" "kyverno" "appName" "kyverno" "component" "core" "meshMode" "none") }}
{{- end }}
