{{- include "bigbang.normalizePackageAliases" . -}}
{{- $gitCredsSecretDict := dict
  "name" "istioEgressGateway"
  "targetScope" .Values.istioEgressGateway
  "releaseName" .Release.Name
  "releaseNamespace" .Release.Namespace
  "enabled" (and (eq (include "egressGatewayEnabled" .) "true") (eq (include "ambientEnabled" .) "true"))
}}
{{- include "gitCredsSecret" $gitCredsSecretDict | nindent 0 -}}
