{{- include "bigbang.normalizePackageAliases" . -}}
{{- if .Values.tempo.enabled }}
{{- include "bigbang.imagePullSecret" (dict "root" . "namespace" "tempo" "appName" "tempo" "component" "core") }}
{{- end }}
