{{- include "bigbang.normalizePackageAliases" . -}}
{{- if and .Values.loki.enabled (not .Values.elasticsearchKibana.enabled) }}
{{- include "bigbang.imagePullSecret" (dict "root" . "namespace" "logging" "appName" "loki" "component" "core") }}
{{- end }}
