{{- if .Values.loki.enabled }}
{{- include "values-secret" (dict "root" $ "package" .Values.loki "name" "loki" "defaults" (include "bigbang.defaults.loki" .)) }}
{{- end }}

{{- define "bigbang.defaults.loki" -}}
hostname: {{ .Values.hostname }}

openshift: {{ .Values.openshift }}

istio:
  enabled: {{ .Values.istio.enabled }}

imagePullSecrets:
  - name: private-registry

image:
  pullPolicy: {{ .Values.imagePullPolicy }}

networkPolicies:
  enabled: {{ .Values.networkPolicies.enabled }}
  controlPlaneCidr: {{ .Values.networkPolicies.controlPlaneCidr }}

monitoring:
  enabled: {{ .Values.monitoring.enabled }}
  serviceMonitor:
    enabled: {{ .Values.monitoring.enabled }}
    # conditional passes only for default istio: enabled, mTLS: SCRICT
    {{- if and .Values.istio.enabled (eq (dig "istio" "mtls" "mode" "STRICT" .Values.loki.values) "STRICT") }}
    scheme: https
    tlsConfig:
      caFile: /etc/prom-certs/root-cert.pem
      certFile: /etc/prom-certs/cert-chain.pem
      keyFile: /etc/prom-certs/key.pem
      insecureSkipVerify: true  # Prometheus does not support Istio security naming, thus skip verifying target pod certificate
    {{- end }}

{{- $disableDefaultFLB := dig "additionalOutputs" "disableDefault" false .Values.fluentbit.values }}
{{- if and .Values.fluentbit.enabled (not $disableDefaultFLB) }}
fluentbit:
  enabled: true
{{- end }}

{{- if .Values.promtail.enabled }}
promtail:
  enabled: true
{{- end }}


loki:
  storage:
    {{- if (eq .Values.loki.strategy "monolith") }}
    type: "filesystem"
    {{- else }}
    type: "s3"
    bucketNames:
      {{- toYaml .Values.loki.objectStorage.bucketNames | nindent 6 }}
    s3:
      {{- if (eq .Values.loki.objectStorage.iamProfile "") }}
      endpoint: {{ .Values.loki.objectStorage.endpoint }}
      {{- end }}
      region: {{ .Values.loki.objectStorage.region }}
      #//{{- if and (not (eq .Values.loki.objectStorage.accessKey "")) (not (eq .Values.loki.objectStorage.accessSecret "")) }}
      {{- with .Values.loki.objectStorage }}
      accessKeyId: {{ .accessKey }}
      secretAccessKey: {{ .accessSecret }}
    {{- end }}
    {{- end }}
  {{- if (eq .Values.loki.strategy "monolith") }}
  rulerConfig:
    storage:
      type: local
  storage_config:
    boltdb_shipper:
      active_index_directory: /var/loki/boltdb-shipper-active
      cache_location: /var/loki/boltdb-shipper-cache
      cache_ttl: 24h
      shared_store: filesystem
    filesystem:
      directory: /var/loki/chunks
  {{- else }}
  storage_config:
    boltdb_shipper:
      active_index_directory: /var/loki/boltdb-shipper-active
      cache_location: /var/loki/boltdb-shipper-cache
      cache_ttl: 24h
      shared_store: s3
    hedging:
      at: 250ms
      max_per_second: 20
      up_to: 3
    tsdb_shipper:
      active_index_directory: /var/loki/tsdb-index
      cache_location: /var/loki/tsdb-cache
      shared_store: s3
      cache_ttl: 24h
  {{- end }}
  {{- if and (eq .Values.loki.strategy "scalable") .Values.loki.objectStorage.iamProfile }}
    aws:
      s3: s3://{{ .Values.loki.objectStorage.region }}/{{ .Values.loki.objectStorage.bucketNames.chunks }}
      region: {{ .Values.loki.objectStorage.region }}
      s3forcepathstyle: false
  rulerConfig:
    storage:
      s3:
        s3: s3://{{ .Values.loki.objectStorage.region }}/{{ .Values.loki.objectStorage.bucketNames.ruler }}
      type: s3
  {{- end }}
  {{- if .Values.istio.enabled }}
  podAnnotations:
    {{ include "istioAnnotation" . }}
  {{- end }}

{{- if (eq .Values.loki.strategy "scalable") }}
singleBinary:
  replicas: 0
{{- end }}

{{- with .Values.loki.objectStorage }}
{{- if and (eq $.Values.loki.strategy "scalable") (not (and .endpoint .region)) }}
minio:
  enabled: true

{{- end }}
{{- if and (eq $.Values.loki.strategy "scalable") (not (eq $.Values.loki.objectStorage.iamProfile "")) }}
serviceAccount:
  create: true
  annotations:
    eks.amazonaws.com/role-arn: {{ $.Values.loki.objectStorage.iamProfile }}
{{- end }}

{{- end }}
{{- end }}

{{- end -}}
