{{- include "bigbang.normalizePackageAliases" . -}}
{{- $gitlabRedis := and (ne .Values.addons.gitlab.redis.password "") (or .Values.addons.gitlab.enabled .Values.addons.gitlabRunner.enabled) -}}
{{- $legacyMonitoringGrafana := dig "upstream" "grafana" "enabled" false .Values.monitoring.values -}}
{{- if and .Values.monitoring.enabled (not .Values.grafana.enabled) $legacyMonitoringGrafana $gitlabRedis }}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-env-secret
  namespace: monitoring
  labels:
    grafana_datasource: "1"
type: Opaque
stringData:
  GITLAB_REDIS_PASSWORD: {{ .Values.addons.gitlab.redis.password }}
{{- end }}
