{{- include "bigbang.normalizePackageAliases" . -}}
{{- $pkg := "harbor" }}
{{- if (get .Values.addons $pkg).enabled }}
{{- include "bigbang.namespace" (dict "root" . "name" $pkg "appName" $pkg "component" "core" "package" (get .Values.addons $pkg)) }}
{{- end }}
