{{- include "bigbang.normalizePackageAliases" . -}}
{{- if .Values.addons.mattermost.enabled }}
{{- include "bigbang.imagePullSecret" (dict "root" . "namespace" "mattermost" "appName" "mattermost" "component" "collaboration-tools") }}
{{- end }}
