{{- include "bigbang.normalizePackageAliases" . -}}
{{- $pkg := "kyvernoReporter" }}
{{- if (get .Values $pkg).enabled }}
{{- include "bigbang.imagePullSecret" (dict "root" . "namespace" "kyverno-reporter" "appName" ($pkg | kebabcase)) }}
{{- end }}
