{{- include "bigbang.normalizePackageAliases" . -}}
{{- if .Values.istioGateway.enabled }}
{{- include "bigbang.imagePullSecret" (dict "root" . "namespace" "istio-gateway" "appName" "private-registry" "component" "istio-gateway") }}
{{- end }}
