{{- include "bigbang.normalizePackageAliases" . -}}
{{- if .Values.addons.vault.enabled }}
{{- include "bigbang.imagePullSecret" (dict "root" . "namespace" "vault" "appName" "vault" "component" "security-tools") }}
{{- end }}
