#!/usr/bin/env bash

set -euo pipefail

REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
METADATA_PATH="${REPO_ROOT}/chart/package-metadata.yaml"
SCHEMA_PATH="${REPO_ROOT}/chart/values.schema.json"
VALUES_PATH="${REPO_ROOT}/chart/values.yaml"
MIGRATION_PATH="${REPO_ROOT}/scripts/migrate-values-3-to-4.sh"
JQ_PROGRAM="${REPO_ROOT}/scripts/generate-package-schemas.jq"
PACKAGES_INDEX_PATH="${REPO_ROOT}/docs/packages/index.md"
CORE_INDEX_PATH="${REPO_ROOT}/docs/packages/core/index.md"
CORE_NAV_PATH="${REPO_ROOT}/docs/packages/core/.pages"
ADDON_INDEX_PATH="${REPO_ROOT}/docs/packages/addons/index.md"
ADDON_NAV_PATH="${REPO_ROOT}/docs/packages/addons/.pages"
MODE=${1:---write}

fail() {
  printf 'Error: %s\n' "$*" >&2
  exit 1
}

if [[ $# -gt 1 || "$MODE" != "--write" && "$MODE" != "--check" ]]; then
  fail "usage: $(basename "$0") [--write|--check]"
fi

command -v jq >/dev/null 2>&1 || fail "jq is required"
command -v yq >/dev/null 2>&1 || fail "Mike Farah yq v4 is required"
[[ "$(yq --version 2>/dev/null)" =~ version\ v4\. ]] || fail "Mike Farah yq v4 is required"

TASK_TMP=$(mktemp -d "${TMPDIR:-/tmp}/bigbang-package-schemas.XXXXXX")
cleanup() {
  rm -f "${TASK_TMP}/metadata.json" "${TASK_TMP}/values.json" \
    "${TASK_TMP}/values.schema.json" "${TASK_TMP}/migrate-values-3-to-4.sh" \
    "${TASK_TMP}/catalog-template-directories" \
    "${TASK_TMP}/integrated-template-directories" \
    "${TASK_TMP}/packages-index.md" "${TASK_TMP}/core-index.md" \
    "${TASK_TMP}/core.pages" "${TASK_TMP}/addon-index.md" \
    "${TASK_TMP}/addon.pages"
  rmdir "$TASK_TMP"
}
trap cleanup EXIT

yq -o=json '.' "$METADATA_PATH" >"${TASK_TMP}/metadata.json"
yq -o=json '.' "$VALUES_PATH" >"${TASK_TMP}/values.json"

# Validate metadata before using its identifiers as filesystem paths or
# emitting its package keys into the generated Bash arrays.
jq --slurpfile metadata "${TASK_TMP}/metadata.json" \
  --slurpfile values "${TASK_TMP}/values.json" \
  -f "$JQ_PROGRAM" "$SCHEMA_PATH" >"${TASK_TMP}/values.schema.json"

yq -r '.packages[].templateDirectory' "$METADATA_PATH" \
  | sort -u >"${TASK_TMP}/catalog-template-directories"

while IFS= read -r template_directory; do
  [[ -d "${REPO_ROOT}/chart/templates/${template_directory}" ]] \
    || fail "template directory chart/templates/${template_directory} does not exist"
done <"${TASK_TMP}/catalog-template-directories"

DOCUMENTATION_PATHS=$(yq -r '.packages[].documentation' "$METADATA_PATH" | sort -u)
while IFS= read -r documentation_path; do
  [[ -f "${REPO_ROOT}/${documentation_path}" ]] \
    || fail "package documentation ${documentation_path} does not exist"
done <<<"$DOCUMENTATION_PATHS"

# Package-specific template directories contain a HelmRelease. The package and
# wrapper directories contain generic renderers rather than integrated packages.
while IFS= read -r helmrelease_path; do
  template_directory=${helmrelease_path%/helmrelease.yaml}
  template_directory=${template_directory##*/}
  if [[ "$template_directory" != "package" && "$template_directory" != "wrapper" ]]; then
    printf '%s\n' "$template_directory"
  fi
done < <(find "${REPO_ROOT}/chart/templates" -mindepth 2 -maxdepth 2 \
  -type f -name helmrelease.yaml -print) \
  | sort -u >"${TASK_TMP}/integrated-template-directories"

while IFS= read -r template_directory; do
  fail "integrated package template directory chart/templates/${template_directory} is missing from chart/package-metadata.yaml"
done < <(comm -23 "${TASK_TMP}/integrated-template-directories" \
  "${TASK_TMP}/catalog-template-directories")

{
  sed -n '1,/^# BEGIN GENERATED PACKAGE METADATA$/p' "$MIGRATION_PATH" | sed '$d'
  printf '%s\n' '# BEGIN GENERATED PACKAGE METADATA'
  printf '%s\n' '# Generated by scripts/generate-package-schemas.sh from chart/package-metadata.yaml.'
  printf '%s\n' 'ROOT_PACKAGES=('
  yq -r '.packages | to_entries[] | select(.value.category == "core") | "  " + .key' "$METADATA_PATH"
  printf '%s\n\n' ')'
  printf '%s\n' 'ADDON_PACKAGES=('
  yq -r '.packages | to_entries[] | select(.value.category == "addon") | "  " + .key' "$METADATA_PATH"
  printf '%s\n\n' ')'
  printf '%s\n' 'BUILTIN_PACKAGE_METADATA=('
  yq -r '.packages | to_entries[] | "  \"" + .key + "|" + .value.templateDirectory + "\""' "$METADATA_PATH"
  printf '%s\n' ')'
  printf '%s\n' '# END GENERATED PACKAGE METADATA'
  sed -n '/^# END GENERATED PACKAGE METADATA$/,$p' "$MIGRATION_PATH" | sed '1d'
} >"${TASK_TMP}/migrate-values-3-to-4.sh"

generate_package_table() {
  local category=$1
  local category_local_links=$2
  local package_rows

  package_rows=$(jq -r --arg category "$category" \
    --slurpfile values "${TASK_TMP}/values.json" \
    '.packages | to_entries | map(select(.value.category == $category))
     | sort_by(.value.displayName | ascii_downcase)[] | . as $package |
     ($values[0] | getpath($package.value.legacyPath | split(".")) | .git.repo | sub("\\.git$"; "")) as $repository |
     [$package.key, $package.value.displayName, $repository, $package.value.documentation] | @tsv' \
    "${TASK_TMP}/metadata.json")

  printf '%s\n' '| Package | Canonical configuration | Big Bang integration | Package source |'
  printf '%s\n' '| --- | --- | --- | --- |'
  while IFS=$'\t' read -r package_name display_name repository_url documentation_path; do
    documentation_path=${documentation_path#docs/packages/}
    if [[ "$category_local_links" == "true" ]]; then
      documentation_path="${documentation_path#*/}"
    fi
    printf '| %s | `%s` | [Guide](%s) | [Repository](%s) |\n' \
      "$display_name" "packages.${package_name}" "$documentation_path" \
      "$repository_url"
  done <<<"$package_rows"
}

generate_category_index() {
  local category=$1
  local display_category=$2
  local output_path=$3

  {
    printf '%s\n\n' '<!-- Generated by scripts/generate-package-schemas.sh from chart/package-metadata.yaml. Do not edit directly. -->'
    printf '# %s Packages\n\n' "$display_category"
    printf 'These packages are integrated directly into the Big Bang umbrella chart. The catalog metadata determines their configuration identity and Big Bang integration guide; `chart/values.yaml` supplies the release-pinned package source.\n\n'
    printf 'Use the integration guide for Big Bang-specific behavior. Use the package repository for the packaged chart values, changelog, and implementation details.\n\n'
    generate_package_table "$category" true
  } >"$output_path"
}

generate_category_nav() {
  local category=$1
  local output_path=$2
  local documentation_paths
  local navigation_rows

  documentation_paths=$(jq -r --arg category "$category" '
    [.packages | to_entries[] | select(.value.category == $category) | .value.documentation]
    | (reduce .[] as $path ([]; if index($path) then . else . + [$path] end))[]' \
    "${TASK_TMP}/metadata.json")

  navigation_rows=$(
    while IFS= read -r documentation_path; do
      local source_path="${REPO_ROOT}/${documentation_path}"
      local filename=${documentation_path##*/}
      local label
      label=$(sed -n 's/^# //p' "$source_path" | sed -n '1p')
      printf '%s\t%s\n' "$label" "$filename"
    done <<<"$documentation_paths" | LC_ALL=C sort -f -t $'\t' -k1,1 -k2,2
  )

  printf '%s\n' 'nav:' >"$output_path"
  printf '%s\n' '  - Overview: index.md' >>"$output_path"
  while IFS=$'\t' read -r label filename; do
    label=${label//\"/\\\"}
    printf '  - "%s": %s\n' "$label" "$filename" >>"$output_path"
  done <<<"$navigation_rows"
}

{
  printf '%s\n\n' '<!-- Generated by scripts/generate-package-schemas.sh from chart/package-metadata.yaml. Do not edit directly. -->'
  printf '%s\n\n' '# Integrated Packages'
  printf '%s\n\n' 'This catalog lists the packages rendered directly by the Big Bang umbrella chart. `chart/package-metadata.yaml` is the source of truth for package identity, category, and Big Bang integration documentation; `chart/values.yaml` supplies the release-pinned package source.'
  printf '%s\n\n' 'Configure built-in packages under `packages.<name>` when using `packageConfiguration.version: v1`. See [Package Management](../concepts/package-management.md) for the configuration model and [Categorization](categorization.md) for package roles and stack relationships.'
  printf '%s\n\n' 'The integration guide covers Big Bang-specific behavior. The package repository owns packaged chart values, implementation details, and its changelog.'
  printf '%s\n\n' '## Core packages'
  printf '%s\n\n' 'Core packages provide the platform capabilities that other packages commonly depend on.'
  generate_package_table core false
  printf '%s\n\n' '## Add-on packages'
  printf '%s\n\n' 'Add-on packages provide optional platform and application capabilities.'
  generate_package_table addon false
  printf '%s\n\n' '## Other package collections'
  printf '%s\n' '- [Maintained packages](https://repo1.dso.mil/groups/big-bang/product/maintained) are maintained and tested independently but are not rendered directly by the umbrella chart.'
  printf '%s\n' '- [Community packages](https://repo1.dso.mil/groups/big-bang/product/community) are owned by community maintainers and are not supported as built-in integrations.'
  printf '%s\n' '- Use [Extra Package Deployment](../installation/environments/extra-package-deployment.md) to deploy a package that is not integrated directly.'
} >"${TASK_TMP}/packages-index.md"

generate_category_index core Core "${TASK_TMP}/core-index.md"
generate_category_nav core "${TASK_TMP}/core.pages"
generate_category_index addon Add-on "${TASK_TMP}/addon-index.md"
generate_category_nav addon "${TASK_TMP}/addon.pages"

if [[ "$MODE" == "--check" ]]; then
  STALE_FILES=()
  cmp -s "$SCHEMA_PATH" "${TASK_TMP}/values.schema.json" || STALE_FILES+=("$SCHEMA_PATH")
  cmp -s "$MIGRATION_PATH" "${TASK_TMP}/migrate-values-3-to-4.sh" || STALE_FILES+=("$MIGRATION_PATH")
  cmp -s "$PACKAGES_INDEX_PATH" "${TASK_TMP}/packages-index.md" || STALE_FILES+=("$PACKAGES_INDEX_PATH")
  cmp -s "$CORE_INDEX_PATH" "${TASK_TMP}/core-index.md" || STALE_FILES+=("$CORE_INDEX_PATH")
  cmp -s "$CORE_NAV_PATH" "${TASK_TMP}/core.pages" || STALE_FILES+=("$CORE_NAV_PATH")
  cmp -s "$ADDON_INDEX_PATH" "${TASK_TMP}/addon-index.md" || STALE_FILES+=("$ADDON_INDEX_PATH")
  cmp -s "$ADDON_NAV_PATH" "${TASK_TMP}/addon.pages" || STALE_FILES+=("$ADDON_NAV_PATH")
  if [[ ${#STALE_FILES[@]} -gt 0 ]]; then
    fail "generated files are stale: ${STALE_FILES[*]}; run scripts/generate-package-schemas.sh --write"
  fi
  printf '%s\n' 'Generated package metadata files are up to date.'
else
  cp "${TASK_TMP}/values.schema.json" "$SCHEMA_PATH"
  cp "${TASK_TMP}/migrate-values-3-to-4.sh" "$MIGRATION_PATH"
  cp "${TASK_TMP}/packages-index.md" "$PACKAGES_INDEX_PATH"
  cp "${TASK_TMP}/core-index.md" "$CORE_INDEX_PATH"
  cp "${TASK_TMP}/core.pages" "$CORE_NAV_PATH"
  cp "${TASK_TMP}/addon-index.md" "$ADDON_INDEX_PATH"
  cp "${TASK_TMP}/addon.pages" "$ADDON_NAV_PATH"
  chmod +x "$MIGRATION_PATH"
  printf '%s\n' 'Updated generated package metadata files.'
fi
