{{- $gitlabRedis := and (ne .Values.addons.gitlab.redis.password "") (or .Values.addons.gitlab.enabled .Values.addons.gitlabRunner.enabled) -}}
{{- if and .Values.grafana.enabled $gitlabRedis }}
apiVersion: v1
kind: Secret
metadata:
  name: grafana-env-secret
  namespace: monitoring
  labels:
     grafana_datasource: "1"
type: Opaque
stringData:
  GITLAB_REDIS_PASSWORD: {{ .Values.addons.gitlab.redis.password }}
{{- end }}
