{{- include "bigbang.normalizePackageAliases" . -}}
{{- if and (not .Values.monitoring.enabled) .Values.grafana.enabled }}
{{- include "bigbang.imagePullSecret" (dict "root" . "namespace" "monitoring" "appName" "monitoring" "component" "core") }}
{{- end }}
