{{- include "bigbang.normalizePackageAliases" . -}}
{{- if or .Values.eckOperator.enabled .Values.elasticsearchKibana.enabled }}
{{- include "bigbang.imagePullSecret" (dict "root" . "namespace" "eck-operator" "appName" "eck-operator" "component" "core") }}
{{- end }}
