{{- include "bigbang.normalizePackageAliases" . -}}
{{- if or .Values.eckOperator.enabled .Values.elasticsearchKibana.enabled }}
{{- include "bigbang.namespace" (dict "root" . "name" "eck-operator" "appName" "eck-operator" "component" "core" "package" .Values.eckOperator) }}
{{- end }}
