{{- include "bigbang.normalizePackageAliases" . -}}
{{- if .Values.addons.externalSecrets.enabled }}
{{- include "bigbang.imagePullSecret" (dict "root" . "namespace" "external-secrets") }}
{{- end }}
