{{- include "bigbang.normalizePackageAliases" . -}}
{{- if .Values.istioCRDs.enabled }}
{{- include "bigbang.imagePullSecret" (dict "root" . "namespace" "istio-system" "appName" "istiod" "component" "core") }}
{{- end }}
