{{- include "bigbang.normalizePackageAliases" . -}}
{{- if .Values.istioCRDs.enabled }}
{{- include "bigbang.namespace" (dict "root" . "name" "istio-system" "appName" "istio-system" "component" "core" "meshMode" "none" "extraLabels" (dict "istio-base-managed" "Reconcile")) }}
{{- if .Values.istioGateway.enabled }}
---
{{ include "bigbang.namespace" (dict "root" . "name" "istio-gateway" "appName" "istio-gateway" "component" "core" "package" .Values.istioGateway "extraLabels" (dict "istio-gateway-managed" "Reconcile")) }}
{{- end }}
{{- end }}
