{{- include "bigbang.normalizePackageAliases" . -}}
{{- $gitCredsSecretDict := dict
  "name" "gatewayAPI"
  "targetScope" .Values.gatewayAPI
  "releaseName" .Release.Name
  "releaseNamespace" .Release.Namespace
  "enabled" (or .Values.gatewayAPI.enabled (eq (include "ambientEnabled" .) "true"))
}}
{{- include "gitCredsSecret" $gitCredsSecretDict | nindent 0 -}}
