{{- $fluxSettingsGatewayAPI := merge .Values.gatewayAPI.flux .Values.flux -}}
{{- if or .Values.gatewayAPI.enabled .Values.istio.ambient.enabled }}
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: gateway-api
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: gateway-api
    app.kubernetes.io/component: "core"
    {{- include "commonLabels" . | nindent 4}}
  annotations:
    checksum/bigbang-values: {{ include (print $.Template.BasePath "/gateway-api/values.yaml") . | sha256sum }}
spec:
  releaseName: gateway-api
  targetNamespace: kube-system
  {{- include "bigbang.helmRelease.chartSpec" (dict "name" "gateway-api" "package" .Values.gatewayAPI "root" .) | nindent 2 }}

  {{- toYaml $fluxSettingsGatewayAPI | nindent 2 }}

  {{- if .Values.gatewayAPI.postRenderers }}
  postRenderers:
  {{ toYaml .Values.gatewayAPI.postRenderers | nindent 4 }}
  {{- end }}
  {{- include "bigbang.helmRelease.valuesFrom" (dict "name" "gateway-api" "root" .) | nindent 2 }}

  {{- if or .Values.gatekeeper.enabled .Values.kyvernoPolicies.enabled }}
  dependsOn:
    {{- if .Values.gatekeeper.enabled }}
    - name: gatekeeper
      namespace: {{ .Release.Namespace }}
    {{- end }}
    {{- if .Values.kyvernoPolicies.enabled }}
    - name: kyverno-policies
      namespace: {{ .Release.Namespace }}
    {{- end }}
  {{- end }}
{{- end }}
