{{- $pkg := "gatewayAPI" }}

{{- /* Create secret */ -}}
{{- if or .Values.gatewayAPI.enabled .Values.istio.ambient.enabled }}
{{- include "values-secret" (dict "root" $ "package" (get .Values $pkg) "name" "gateway-api" "defaults" (include "bigbang.defaults.gateway-api" .)) }}
{{- end }}

{{- define "bigbang.defaults.gateway-api" -}}
{{- end }}
