{{- include "bigbang.normalizePackageAliases" . -}}
{{- $gitCredsSecretDict := dict
  "name" "istioCNI"
  "targetScope" .Values.istioCNI
  "releaseName" .Release.Name
  "releaseNamespace" .Release.Namespace
  "enabled" (or .Values.istioCNI.enabled (eq (include "ambientEnabled" .) "true"))
}}
{{- include "gitCredsSecret" $gitCredsSecretDict | nindent 0 -}}
