{{- include "bigbang.normalizePackageAliases" . -}}
{{- if or .Values.istioCNI.enabled (eq (include "ambientEnabled" .) "true") }}
{{- include "bigbang.imagePullSecret" (dict "root" . "namespace" "kube-system" "appName" "istio-cni" "component" "core") }}
{{- end }}
